//! Regression coverage for alef task #47: bumping only the `[workspace] alef_version` pin in
//! `alef.toml` must not change a single byte of any generated output, including the embedded
//! `alef:hash:` line. `compute_inputs_hash` (src/core/hash.rs) already strips that one key
//! before hashing (`strip_alef_version_pin`), but that unit-level guarantee does not by itself
//! prove the real `alef generate` write path (`write_files_report` + `finalize_hashes`) leaves
//! every file byte-identical on disk -- this drives the actual CLI binary over two full
//! generation runs and diffs the resulting trees.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn alef_binary() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_alef"))
}

fn write_fixture(root: &Path, alef_version: &str) {
    fs::create_dir_all(root.join("src")).expect("create fixture source directory");
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"pin-stability-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write fixture Cargo.toml");
    fs::write(
        root.join("src/lib.rs"),
        "pub struct Record { pub value: String }\n\npub fn record_value(record: Record) -> String { record.value }\n",
    )
    .expect("write fixture source");
    fs::write(
        root.join("alef.toml"),
        format!(
            "[workspace]\nalef_version = \"{alef_version}\"\nlanguages = [\"go\", \"zig\"]\n\n\
             [[crates]]\nname = \"pin-stability-fixture\"\nsources = [\"src/lib.rs\"]\n\
             version_from = \"Cargo.toml\"\n\n[crates.generate]\npublic_api = false\n",
        ),
    )
    .expect("write alef config");
}

/// Swift is deliberately excluded from this fixture's `languages`: its post-build step
/// (`MaterializeSwiftBridge`) reads real `cargo build` output under `target/`, whose presence
/// depends on run ordering rather than on generation inputs, so it is not idempotent by
/// construction -- exactly why `tests/cli_generate_atomicity.rs` needs a fake `cargo` and a
/// `PROTECTED_PATHS` allowlist just to assert anything about it. `go` and `zig` alone exercise
/// the FFI-dependent write path this test cares about without that unrelated hazard.
fn run_generate(root: &Path) -> Output {
    Command::new(alef_binary())
        .current_dir(root)
        .args(["generate", "--lang", "go,zig"])
        .output()
        .expect("run alef generate")
}

/// Every file under `root`, excluding alef's own bookkeeping (`.alef/`) and `alef.toml` itself
/// (which legitimately differs by design: that is the pin being bumped, not an output the
/// generator produced), mapped to its bytes.
fn snapshot_generated_tree(root: &Path) -> std::collections::BTreeMap<PathBuf, Vec<u8>> {
    walkdir::WalkDir::new(root)
        .into_iter()
        .filter_entry(|entry| {
            let name = entry.file_name().to_string_lossy();
            name != ".alef" && name != ".git"
        })
        .filter_map(Result::ok)
        .filter(|entry| entry.file_type().is_file())
        .map(walkdir::DirEntry::into_path)
        .filter(|path| path.file_name().is_some_and(|name| name != "alef.toml"))
        .map(|path| {
            let relative = path.strip_prefix(root).expect("entry under root").to_path_buf();
            let bytes = fs::read(&path).unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
            (relative, bytes)
        })
        .collect()
}

/// Bumping only the `alef_version` pin between two `alef generate` runs must not change a single
/// generated byte -- not content, not the embedded `alef:hash:` line. This is the write-path
/// counterpart to `core::hash::tests::inputs_hash_alef_version_pin_table`, which proves the same
/// property for `compute_inputs_hash` in isolation; this test proves it survives the full
/// `write_files_report` + `finalize_hashes` round trip the way a real consumer upgrade does.
#[test]
fn version_pin_bump_alone_leaves_every_generated_file_byte_identical() {
    let fixture = tempfile::tempdir().expect("create fixture directory");
    let root = fixture.path();
    write_fixture(root, "0.61.0");

    let first = run_generate(root);
    assert!(
        first.status.success(),
        "first generate failed: {}",
        String::from_utf8_lossy(&first.stderr)
    );
    let before = snapshot_generated_tree(root);
    assert!(!before.is_empty(), "fixture produced no generated files to compare");

    let alef_toml = root.join("alef.toml");
    let bumped = fs::read_to_string(&alef_toml)
        .expect("read alef.toml")
        .replace("alef_version = \"0.61.0\"", "alef_version = \"0.61.1\"");
    fs::write(&alef_toml, bumped).expect("bump alef_version pin");

    let second = run_generate(root);
    assert!(
        second.status.success(),
        "second generate failed: {}",
        String::from_utf8_lossy(&second.stderr)
    );
    let after = snapshot_generated_tree(root);

    let before_paths: std::collections::BTreeSet<_> = before.keys().collect();
    let after_paths: std::collections::BTreeSet<_> = after.keys().collect();
    assert_eq!(
        before_paths, after_paths,
        "the version-pin-only bump changed the set of generated files"
    );

    let mut mismatches = Vec::new();
    for (path, before_bytes) in &before {
        let after_bytes = &after[path];
        if before_bytes != after_bytes {
            mismatches.push(path.display().to_string());
        }
    }
    assert!(
        mismatches.is_empty(),
        "version-pin-only bump changed {} file(s) with no codegen input change: {mismatches:?}",
        mismatches.len()
    );
}

/// Control for the test above: proves `snapshot_generated_tree`'s byte comparison actually
/// detects a real change, so a harness bug that always reported "identical" (which would make
/// the pin-stability test above pass vacuously, regardless of whether the production fix is
/// present) cannot hide behind it. Adding a field to the source type changes the extracted IR,
/// which must reach at least one generated file.
#[test]
fn real_source_change_still_changes_generated_files() {
    let fixture = tempfile::tempdir().expect("create fixture directory");
    let root = fixture.path();
    write_fixture(root, "0.61.0");

    let first = run_generate(root);
    assert!(
        first.status.success(),
        "first generate failed: {}",
        String::from_utf8_lossy(&first.stderr)
    );
    let before = snapshot_generated_tree(root);

    fs::write(
        root.join("src/lib.rs"),
        "pub struct Record { pub value: String, pub extra: i64 }\n\n\
         pub fn record_value(record: Record) -> String { record.value }\n",
    )
    .expect("write changed fixture source");

    let second = run_generate(root);
    assert!(
        second.status.success(),
        "second generate failed: {}",
        String::from_utf8_lossy(&second.stderr)
    );
    let after = snapshot_generated_tree(root);

    let changed = before
        .iter()
        .filter(|(path, before_bytes)| after.get(*path).is_some_and(|after_bytes| after_bytes != *before_bytes))
        .count();
    assert!(
        changed > 0,
        "a real IR-affecting source change produced zero changed files -- the comparison harness \
         cannot distinguish a real regeneration from a no-op"
    );
}
