//! Regression tests for the fixture-level `preserve_input_urls` flag.
//!
//! `mock_url` / `mock_url_list` arguments bind the mock server address and ignore the
//! fixture's declared `input.url` entirely. That is correct for almost every fixture —
//! they need a live server to talk to — but silently wrong for the minority whose
//! subject IS the address: SSRF policy, scheme rejection, host parsing. Three SSRF
//! fixtures declaring `http://127.0.0.1:9/`, `http://[::ffff:127.0.0.1]/` and
//! `http://[64:ff9b::7f00:1]/` all generated byte-identical calls against the mock
//! server, so they proved one trivial thing three times and could not fail.
//!
//! Each language is asserted from two directions, because a fix that preserved the URL
//! by breaking the mock-server default would trade one silent-wrongness for another:
//!   1. default (`preserve_input_urls` absent) still substitutes the mock server, and
//!   2. opted-in fixtures emit the declared address verbatim.

use alef::core::config::NewAlefConfig;
use alef::e2e::codegen::E2eCodegen;
use alef::e2e::codegen::rust::RustE2eCodegen;
use alef::e2e::codegen::{
    c::CCodegen, csharp::CSharpCodegen, dart::DartE2eCodegen, elixir::ElixirCodegen, gleam::GleamE2eCodegen,
    go::GoCodegen, java::JavaCodegen, kotlin::KotlinE2eCodegen, php::PhpCodegen, python::PythonE2eCodegen,
    ruby::RubyCodegen, swift::SwiftE2eCodegen, typescript::TypeScriptCodegen, zig::ZigE2eCodegen,
};
use alef::e2e::fixture::{Assertion, Fixture, FixtureGroup};

/// The loopback address an opted-in fixture declares. Deliberately not a URL any mock
/// server would ever hand out, so a substituted URL cannot coincidentally match.
const DECLARED_URL: &str = "http://[::ffff:127.0.0.1]/";

fn build_config(
    language: &str,
    arg_type: &str,
) -> (alef::e2e::config::E2eConfig, alef::core::config::ResolvedCrateConfig) {
    let field = if arg_type == "mock_url_list" { "urls" } else { "url" };
    let toml_src = format!(
        r#"
[workspace]
languages = ["{language}"]

[[crates]]
name = "demo_crawler"
sources = ["src/lib.rs"]

[crates.e2e]
fixtures = "fixtures"
output = "e2e"

[crates.e2e.call]
function = "scrape"
module = "DemoCrawler"
result_var = "result"
async = true
returns_result = true

[[crates.e2e.call.args]]
name = "url"
field = "input.{field}"
type = "{arg_type}"
"#,
    );
    let cfg: NewAlefConfig = toml::from_str(&toml_src).expect("config parses");
    let e2e = cfg.crates[0].e2e.clone().unwrap();
    let resolved = cfg.resolve().expect("resolves").remove(0);
    (e2e, resolved)
}

fn build_fixture(preserve: bool, input: serde_json::Value) -> FixtureGroup {
    FixtureGroup {
        category: "validation".to_string(),
        fixtures: vec![Fixture {
            id: "validation_ssrf_loopback_denied".to_string(),
            category: Some("validation".to_string()),
            description: "SSRF policy rejects a loopback address".to_string(),
            input,
            preserve_input_urls: preserve,
            assertions: vec![Assertion {
                assertion_type: "not_error".to_string(),
                ..Assertion::default()
            }],
            source: "validation.json".to_string(),
            ..Fixture::default()
        }],
    }
}

fn generate(
    codegen: &dyn E2eCodegen,
    language: &str,
    arg_type: &str,
    preserve: bool,
    input: serde_json::Value,
) -> String {
    let (e2e, resolved) = build_config(language, arg_type);
    let groups = vec![build_fixture(preserve, input)];
    codegen
        .generate(&groups, &e2e, &resolved, &[], &[], &[], &[])
        .expect("generation succeeds")
        .iter()
        .map(|f| f.content.clone())
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn rust_default_still_substitutes_the_mock_server_url() {
    let content = generate(
        &RustE2eCodegen,
        "rust",
        "mock_url",
        false,
        serde_json::json!({ "url": DECLARED_URL }),
    );

    // ~keep The negative half of the contract. A fixture that has NOT opted in must
    // keep resolving the mock server at runtime even though it declares a url — most
    // fixtures declare one purely as documentation, and preserving it for them would
    // point the whole suite at addresses with no server behind them.
    assert!(
        content.contains("MOCK_SERVER_VALIDATION_SSRF_LOOPBACK_DENIED"),
        "default path must still bind the per-fixture mock server env var:\n{content}"
    );
    assert!(
        !content.contains(DECLARED_URL),
        "default path must NOT emit the declared url verbatim:\n{content}"
    );
}

#[test]
fn rust_preserve_input_urls_emits_the_declared_address_verbatim() {
    let content = generate(
        &RustE2eCodegen,
        "rust",
        "mock_url",
        true,
        serde_json::json!({ "url": DECLARED_URL }),
    );

    assert!(
        content.contains(DECLARED_URL),
        "opted-in fixture must pass its declared address to the call:\n{content}"
    );
    // ~keep Emitting the address while ALSO consulting the mock server would leave the
    // env var able to override it, which is the original defect wearing a disguise.
    assert!(
        !content.contains("MOCK_SERVER_VALIDATION_SSRF_LOOPBACK_DENIED"),
        "opted-in fixture must not fall back to the mock server env var:\n{content}"
    );
}

#[test]
fn rust_preserve_input_urls_keeps_every_element_of_a_url_list() {
    let second = "http://[64:ff9b::7f00:1]/";
    let content = generate(
        &RustE2eCodegen,
        "rust",
        "mock_url_list",
        true,
        serde_json::json!({ "urls": [DECLARED_URL, second] }),
    );

    assert!(
        content.contains(DECLARED_URL),
        "first declared url missing from generated list:\n{content}"
    );
    assert!(
        content.contains(second),
        "second declared url missing from generated list:\n{content}"
    );
    // ~keep The default list path prefixes relative entries with a runtime base var.
    // Preserved lists must not, or the address under test becomes a suffix of the mock
    // server's.
    assert!(
        !content.contains("url_base"),
        "preserved list must not emit the mock-server base binding:\n{content}"
    );
}

#[test]
fn rust_default_url_list_still_prefixes_relative_paths() {
    let content = generate(
        &RustE2eCodegen,
        "rust",
        "mock_url_list",
        false,
        serde_json::json!({ "urls": ["/seed1", "/seed2"] }),
    );

    assert!(
        content.contains("url_base"),
        "default list path must still resolve a mock-server base:\n{content}"
    );
    assert!(
        content.contains("/seed1") && content.contains("/seed2"),
        "default list path must still carry the declared relative paths:\n{content}"
    );
}

#[test]
fn generated_backends_preserve_scalar_and_list_urls() {
    let backends: &[(&str, &dyn E2eCodegen)] = &[
        ("python", &PythonE2eCodegen),
        ("node", &TypeScriptCodegen),
        ("go", &GoCodegen),
        ("java", &JavaCodegen),
        ("kotlin", &KotlinE2eCodegen),
        ("csharp", &CSharpCodegen),
        ("dart", &DartE2eCodegen),
        ("swift", &SwiftE2eCodegen),
        ("ruby", &RubyCodegen),
        ("php", &PhpCodegen),
        ("elixir", &ElixirCodegen),
        ("gleam", &GleamE2eCodegen),
        ("zig", &ZigE2eCodegen),
        ("c", &CCodegen),
    ];
    let second = "file:///tmp/example";

    for (language, codegen) in backends {
        let scalar = generate(
            *codegen,
            language,
            "mock_url",
            true,
            serde_json::json!({"url": DECLARED_URL}),
        );
        assert!(
            scalar.contains(DECLARED_URL),
            "{language} dropped scalar URL:\n{scalar}"
        );

        let list = generate(
            *codegen,
            language,
            "mock_url_list",
            true,
            serde_json::json!({"urls": [DECLARED_URL, second]}),
        );
        assert!(
            list.contains(DECLARED_URL) && list.contains(second),
            "{language} dropped list URL:\n{list}"
        );

        // ~keep The escaping half. Round-tripping a benign URL proves only that the
        // value survives; it cannot catch a quoting bug, because this suite asserts on
        // the generated *string* and never on whether that string parses in the target
        // language. A previous fix in this area shipped PHP that did not parse, and a
        // brew script that let the shell re-expand `$(...)`, while the unit tests
        // stayed green for both. So assert the metacharacters never reach the output
        // raw, for whichever of them the language actually treats as special.
        let hostile = generate(
            *codegen,
            language,
            "mock_url",
            true,
            serde_json::json!({ "url": HOSTILE_URL }),
        );
        for required in required_escapes_for(language) {
            assert!(
                hostile.contains(required),
                "{language} did not escape `{required}` — the emitted literal can \
                 interpolate or break out of its quoting:\n{hostile}"
            );
        }
    }
}

/// A URL carrying the metacharacters the emitters have historically mishandled:
/// shell command substitution, Ruby/Elixir `#{}`, Kotlin/PHP `$`, and a double quote.
const HOSTILE_URL: &str = "http://127.0.0.1:9/?a=$(id)&b=#{2}&c=\"q\"";

/// Escape sequences that MUST appear in `language`'s emitted literal for [`HOSTILE_URL`].
///
/// ~keep Asserting on the *presence of the escape* rather than the *absence of the raw
/// character*, because the raw character is unavoidable: `"` delimits string literals in
/// most of these languages, so "output contains a quote" is true of every correct file
/// and tests nothing. What distinguishes correct from broken is whether the quote coming
/// **from the URL** was escaped, which `\"` witnesses.
///
/// Per-language, not global, because the right answer depends on the quoting style the
/// emitter chose: Ruby and Dart wrap these values in single quotes, where `"` needs no
/// escape and demanding one would fail a correct emitter. Their interpolation triggers
/// are inert in single quotes for the same reason, so they assert nothing here and are
/// covered by the round-trip assertions above.
fn required_escapes_for(language: &str) -> &'static [&'static str] {
    match language {
        // Single-quoted literals: nothing in HOSTILE_URL is special.
        "ruby" | "dart" => &[],
        // Go emits a backtick raw string, in which no character in HOSTILE_URL is
        // special. Assert that form explicitly — `go_string_literal` falls back to a
        // quoted, escaped literal only when the value itself contains a backtick, so
        // seeing the raw form here is the correct outcome, not a missing escape.
        "go" => &["`http://127.0.0.1:9/?a=$(id)&b=#{2}&c=\"q\"`"],
        // Double-quoted, and `#{` would interpolate.
        "elixir" => &["\\\"", "\\#"],
        // Double-quoted, and a bare `$` starts a template expression.
        "kotlin" | "php" => &["\\\"", "\\$"],
        // Double-quoted, no interpolation in a plain literal.
        _ => &["\\\""],
    }
}
