use alef::cli::pipeline::{finalize_hashes, managed_output_paths, sweep_manifest_orphans, write_files_report};
use alef::core::backend::GeneratedFile;
use alef::core::config::Language;
use alef::core::hash;

const INLINE_MARKER: &str = "// Generated by alef Java bindings\n";

#[test]
fn inline_marked_output_without_generated_header_is_managed_and_rehashed() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("Inline.java");
    let previous = hash::inject_hash_line(
        &format!("{INLINE_MARKER}public final class Previous {{}}\n"),
        &"0".repeat(64),
    );
    std::fs::write(&path, previous).expect("seed previous output");
    let files = vec![inline_generated_file("Inline.java")];

    write_files_report(&[(Language::Java, files.clone())], dir.path()).expect("refresh inline-managed output");
    let managed_paths = managed_output_paths(&files, dir.path());
    let config = b"[crate]\nname = 'sample'\n";
    let updated = finalize_hashes(&managed_paths, "sources", config).expect("finalize inline-managed output");

    let output = std::fs::read_to_string(&path).expect("read finalized output");
    let inputs_hash = hash::compute_inputs_hash("sources", config);
    let expected_hash = hash::compute_file_hash(&inputs_hash, &hash::strip_hash_line(&output));
    let expected_output = hash::inject_hash_line(
        &format!("{INLINE_MARKER}public final class Current {{}}\n"),
        &expected_hash,
    );
    assert_eq!(managed_paths, [path].into_iter().collect());
    assert_eq!(updated, 1);
    assert_eq!(output, expected_output);
    assert_eq!(hash::extract_hash(&output), Some(expected_hash));
}

#[test]
fn all_upgrade_preserves_inline_managed_output_and_unmanaged_scaffold_from_old_manifest() {
    let dir = tempfile::tempdir().expect("tempdir");
    let selected = dir.path().join("java");
    std::fs::create_dir_all(&selected).expect("selected root");
    let inline_path = selected.join("Inline.java");
    let scaffold_path = selected.join("settings.gradle.kts");
    let previous_inline = hash::inject_hash_line(
        &format!("{INLINE_MARKER}public final class Previous {{}}\n"),
        &"0".repeat(64),
    );
    std::fs::write(&inline_path, previous_inline).expect("seed previous inline output");
    std::fs::write(
        &scaffold_path,
        format!("// alef:hash:{}\nrootProject.name = \"sample\"\n", "0".repeat(64)),
    )
    .expect("seed legacy scaffold manifest entry");
    let inline_files = vec![inline_generated_file("java/Inline.java")];
    let generated_outputs = vec![
        inline_files[0].clone(),
        GeneratedFile {
            path: "java/settings.gradle.kts".into(),
            content: "rootProject.name = \"sample\"\n".into(),
            generated_header: false,
        },
    ];

    write_files_report(&[(Language::Java, inline_files)], dir.path()).expect("refresh inline output");
    let keep = managed_output_paths(&generated_outputs, dir.path());
    finalize_hashes(&keep, "sources", b"config").expect("finalize inline output");
    let previous_paths = vec![inline_path.clone(), scaffold_path.clone()];
    // Empty disk-scan roots: this pins the manifest route, whose ownership evidence is
    // `previous_paths` membership. Passing the root here too would additionally exercise the
    // disk-scan route and make a pass ambiguous about which route reclaimed the file. ~keep
    let removed = sweep_manifest_orphans(&previous_paths, &keep, &[selected], &[]).expect("all cleanup selection");

    let inline = std::fs::read_to_string(&inline_path).expect("inline output survives");
    let inputs_hash = hash::compute_inputs_hash("sources", b"config");
    let expected_hash = hash::compute_file_hash(
        &inputs_hash,
        &format!("{INLINE_MARKER}public final class Current {{}}\n"),
    );
    let expected_inline = hash::inject_hash_line(
        &format!("{INLINE_MARKER}public final class Current {{}}\n"),
        &expected_hash,
    );
    let expected_scaffold = format!("// alef:hash:{}\nrootProject.name = \"sample\"\n", "0".repeat(64));
    assert_eq!(removed, 0);
    assert_eq!(inline, expected_inline);
    assert_eq!(
        std::fs::read_to_string(&scaffold_path).expect("scaffold survives"),
        expected_scaffold
    );
    assert!(!keep.contains(&scaffold_path));
}

fn inline_generated_file(path: &str) -> GeneratedFile {
    GeneratedFile {
        path: path.into(),
        content: format!("{INLINE_MARKER}public final class Current {{}}\n"),
        generated_header: false,
    }
}
