//! Two invariants a regenerated binding manifest has to hold, both observed failing in a
//! consumer's tree:
//!
//! 1. It may raise a dependency version, never lower one. Binding manifests are rewritten
//!    in full on every run from literals baked into the emitters, so a literal that has
//!    fallen behind reverts the consumer's own bump on every regeneration.
//! 2. Any rationale comment it emits carries `~keep`. Poly's uncomment pass runs between
//!    regenerations and deletes unmarked comments, so an unmarked rationale is lost in a
//!    commit that reads as unrelated formatting.

use alef::core::config::NewAlefConfig;
use alef::{ApiSurface, Language, ResolvedCrateConfig};

/// Well above any literal an emitter carries or that Renovate will bump one to, so these
/// tests keep testing the floor rather than quietly starting to compare equal versions.
const COMMITTED_BASE64: &str = "0.99";

const CRATE_CONFIG: &str = r#"
[workspace]
languages = ["kotlin_android", "jni"]

[[crates]]
name = "demo-lib"
sources = ["src/lib.rs"]

[crates.kotlin_android]
package = "dev.sample_crate.demo"
namespace = "dev.sample_crate.demo"
"#;

const SCAFFOLDED_LANGUAGES: [Language; 1] = [Language::Jni];

/// The JNI manifest's path relative to the workspace root, as `scaffold_jni` derives it
/// from `[[crates]] name`.
const JNI_MANIFEST: &str = "crates/demo-lib-jni/Cargo.toml";

/// Build a workspace whose root manifest declares `[workspace.dependencies]` but *not*
/// `base64`.
///
/// Both halves matter. Declaring the table stops `workspace_dep_specs`' upward walk at this
/// tempdir instead of letting it find some real manifest above it, and omitting `base64`
/// is what puts the emitter on its hardcoded fallback literal — the only path on which a
/// downgrade is possible at all. A fixture that declared `base64` there would emit
/// `base64.workspace = true` and assert nothing.
fn workspace_with_committed_manifest(committed_jni_manifest: Option<&str>) -> tempfile::TempDir {
    let workspace = tempfile::tempdir().expect("create workspace");
    std::fs::write(
        workspace.path().join("Cargo.toml"),
        "[workspace]\nmembers = []\n\n[workspace.dependencies]\nanyhow = \"1\"\n",
    )
    .expect("write workspace manifest");

    if let Some(contents) = committed_jni_manifest {
        let manifest = workspace.path().join(JNI_MANIFEST);
        std::fs::create_dir_all(manifest.parent().expect("manifest has a parent")).expect("create crate dir");
        std::fs::write(&manifest, contents).expect("write committed manifest");
    }
    workspace
}

fn resolved_config(workspace_root: &std::path::Path) -> ResolvedCrateConfig {
    let parsed: NewAlefConfig = toml::from_str(CRATE_CONFIG).expect("config parses");
    let mut config = parsed.resolve().expect("config resolves").remove(0);
    config.workspace_root = Some(workspace_root.to_path_buf());
    config
}

fn scaffold_jni_manifest(workspace_root: &std::path::Path) -> String {
    let config = resolved_config(workspace_root);
    let files =
        alef::scaffold::scaffold(&ApiSurface::default(), &config, &SCAFFOLDED_LANGUAGES).expect("scaffold succeeds");
    files
        .iter()
        .find(|file| file.path == std::path::Path::new(JNI_MANIFEST))
        .unwrap_or_else(|| {
            let emitted: Vec<String> = files.iter().map(|file| file.path.display().to_string()).collect();
            panic!("`{JNI_MANIFEST}` must be scaffolded; got: {emitted:?}")
        })
        .content
        .clone()
}

fn dependency_line(manifest: &str, name: &str) -> String {
    manifest
        .lines()
        .find(|line| line.starts_with(&format!("{name} ")))
        .unwrap_or_else(|| panic!("`{name}` must appear in:\n{manifest}"))
        .to_string()
}

/// The anti-vacuity control the downgrade test depends on: with no committed manifest the
/// emitter really does write a bare `base64 = "<literal>"` line. If this ever stops holding
/// — the fallback path is dropped, the dep is renamed, the entry becomes a table — the test
/// below would pass while comparing nothing.
#[test]
fn scaffolded_jni_manifest_emits_a_bare_base64_literal_when_nothing_is_committed() {
    let workspace = workspace_with_committed_manifest(None);

    let manifest = scaffold_jni_manifest(workspace.path());

    let line = dependency_line(&manifest, "base64");
    assert!(
        line.starts_with("base64 = \"") && !line.contains("workspace"),
        "the fallback literal path must be the one under test, got: {line}"
    );
}

/// The reported defect. A consumer already on a higher `base64` must not have it written
/// back down by a regeneration; otherwise the bump has to be reapplied by hand every time.
#[test]
fn scaffolded_jni_manifest_never_lowers_a_version_the_committed_manifest_already_carries() {
    let committed =
        format!("# Generated by alef. Do not edit by hand.\n\n[dependencies]\nbase64 = \"{COMMITTED_BASE64}\"\n");
    let workspace = workspace_with_committed_manifest(Some(&committed));

    let manifest = scaffold_jni_manifest(workspace.path());

    assert_eq!(
        dependency_line(&manifest, "base64"),
        format!("base64 = \"{COMMITTED_BASE64}\""),
        "the emitted manifest must not lower a committed dependency version:\n{manifest}"
    );
}

/// Convergence: the floor makes rendered output depend on disk state, so feeding the
/// emitted manifest back as the committed one must be a fixed point. Without this, `alef
/// verify` could report a manifest permanently stale against its own output.
#[test]
fn scaffolded_jni_manifest_is_stable_when_regenerated_over_its_own_output() {
    let first = {
        let committed = format!("[dependencies]\nbase64 = \"{COMMITTED_BASE64}\"\n");
        let workspace = workspace_with_committed_manifest(Some(&committed));
        scaffold_jni_manifest(workspace.path())
    };

    let workspace = workspace_with_committed_manifest(Some(&first));
    let second = scaffold_jni_manifest(workspace.path());

    assert_eq!(
        second, first,
        "a regeneration over alef's own output must change nothing"
    );
}

/// The `~keep` marker fix. Alef replaces whatever rationale a consumer hand-wrote above the
/// lints block with its own paraphrase; the replacement has to be at least as durable as
/// what it displaced, or poly's next uncomment pass deletes the reasoning entirely.
#[test]
fn scaffolded_jni_manifest_marks_its_lints_rationale_comment_with_keep() {
    let workspace = workspace_with_committed_manifest(None);

    let manifest = scaffold_jni_manifest(workspace.path());

    let block = comment_block_containing(&manifest, "deliberately does not use");
    assert!(
        block.contains("~keep"),
        "the emitted lints rationale must carry `~keep` so poly's uncomment pass spares it, got:\n{block}"
    );
}

/// Emitted comments must not carry trailing whitespace: the in-memory `GeneratedFile`
/// content is what gets hashed, while the bytes written to disk are whitespace-normalised,
/// so a trailing space here makes a freshly-written file read back as modified.
#[test]
fn scaffolded_jni_manifest_rationale_has_no_trailing_whitespace() {
    let workspace = workspace_with_committed_manifest(None);

    let manifest = scaffold_jni_manifest(workspace.path());

    for line in comment_block_containing(&manifest, "deliberately does not use").lines() {
        assert_eq!(
            line.trim_end(),
            line,
            "rationale line has trailing whitespace: {line:?}"
        );
    }
}

/// The contiguous run of `#` lines containing `needle`. The `~keep` marker is block-scoped
/// in poly's uncomment engine — one marker anywhere in an unbroken comment run spares the
/// whole run — so the block, not the single line, is the unit that must be checked.
fn comment_block_containing(manifest: &str, needle: &str) -> String {
    let lines: Vec<&str> = manifest.lines().collect();
    let index = lines
        .iter()
        .position(|line| line.contains(needle))
        .unwrap_or_else(|| panic!("no comment containing {needle:?} in:\n{manifest}"));

    let is_comment = |line: &&str| line.trim_start().starts_with('#');
    let start = lines[..index]
        .iter()
        .rposition(|line| !is_comment(line))
        .map_or(0, |position| position + 1);
    let end = lines[index..]
        .iter()
        .position(|line| !is_comment(line))
        .map_or(lines.len(), |offset| index + offset);
    lines[start..end].join("\n")
}
