//! `.editorconfig` emitter — provides per-project editor style settings.
//!
//! Kotlin sources are canonically formatted with ktfmt (`--kotlinlang-style`),
//! the single formatter for the emitted tree; these settings only guide editors
//! and non-Kotlin files.

/// Emit `.editorconfig` for the AAR project root.
pub fn emit() -> String {
    String::from(
        r#"# Generated by alef. Do not edit by hand.
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.kt]
indent_style = space
indent_size = 4

[*.gradle.kts]
indent_style = space
indent_size = 4

[*.{xml,pro,gitignore}]
indent_style = space
indent_size = 2
"#,
    )
}
