use super::normalization::normalize_content;
use crate::core::backend::GeneratedFile;
use crate::core::config::Language;
use crate::core::hash;
use anyhow::Context as _;
use base64::Engine;
use rayon::prelude::*;
use std::path::Path;
use tracing::debug;

const HASH_HEADER_SCAN_LINES: usize = 10;

#[derive(Debug, Default)]
pub struct WriteReport {
    pub expected_paths: std::collections::HashSet<std::path::PathBuf>,
    pub changed_paths: std::collections::HashSet<std::path::PathBuf>,
}

impl WriteReport {
    pub fn changed_count(&self) -> usize {
        self.changed_paths.len()
    }
}

pub fn managed_output_paths(files: &[GeneratedFile], base_dir: &Path) -> std::collections::HashSet<std::path::PathBuf> {
    files
        .iter()
        .filter(|file| file.generated_header)
        .map(|file| base_dir.join(&file.path))
        .collect()
}

pub(crate) fn atomic_write(path: &Path, content: &[u8]) -> anyhow::Result<()> {
    let parent = path.parent().context("generated output path has no parent")?;
    let mut temporary = tempfile::NamedTempFile::new_in(parent)
        .with_context(|| format!("failed to create temporary file in {}", parent.display()))?;
    if let Ok(metadata) = std::fs::metadata(path) {
        temporary
            .as_file()
            .set_permissions(metadata.permissions())
            .with_context(|| format!("failed to preserve permissions for {}", path.display()))?;
    }
    std::io::Write::write_all(&mut temporary, content)
        .with_context(|| format!("failed to write temporary file for {}", path.display()))?;
    temporary
        .persist(path)
        .map_err(|error| error.error)
        .with_context(|| format!("failed to replace {}", path.display()))?;
    Ok(())
}

pub(super) fn ensure_generated_header(path: &Path, content: &str) -> String {
    let has_marker = content
        .lines()
        .take(HASH_HEADER_SCAN_LINES)
        .any(|line| line.contains("auto-generated by alef") || line.contains("Generated by alef"));
    if has_marker {
        return content.to_owned();
    }

    let style = match path.extension().and_then(|extension| extension.to_str()) {
        Some("py" | "rb" | "r" | "ex" | "exs" | "toml" | "yaml" | "yml" | "sh") => hash::CommentStyle::Hash,
        Some("h" | "hpp") => hash::CommentStyle::Block,
        Some(
            "c" | "cc" | "cpp" | "cs" | "dart" | "gleam" | "go" | "java" | "js" | "kt" | "kts" | "php" | "rs" | "swift"
            | "ts" | "tsx" | "zig",
        ) => hash::CommentStyle::DoubleSlash,
        _ => return content.to_owned(),
    };
    let header = hash::header(style);
    if let Some((shebang, body)) = content.split_once('\n').filter(|(line, _)| line.starts_with("#!/")) {
        return format!("{shebang}\n{header}\n{body}");
    }
    if let Some((opening_tag, body)) = content.split_once('\n').filter(|(line, _)| line.trim() == "<?php") {
        return format!("{opening_tag}\n{header}\n{body}");
    }
    format!("{header}\n{content}")
}

/// Apply `0o755` permissions to a file whose content begins with a shebang line.
///
/// Called immediately after every `fs::write` in both [`write_files`] and
/// [`write_scaffold_files_with_overwrite`] so that generated shell scripts
/// (e.g. `download_ffi.sh`, `run_tests.sh`, `mvnw`) are executable on Unix
/// without a manual `chmod` step by the consumer.
///
/// On non-Unix platforms this is a no-op — POSIX permission bits do not exist.
#[cfg(unix)]
pub(crate) fn apply_shebang_chmod(path: &std::path::Path, content: &str) -> anyhow::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    if content.starts_with("#!") {
        let perms = std::fs::Permissions::from_mode(0o755);
        std::fs::set_permissions(path, perms).with_context(|| format!("failed to chmod 755 {}", path.display()))?;
    }
    Ok(())
}

#[cfg(not(unix))]
pub(crate) fn apply_shebang_chmod(_path: &std::path::Path, _content: &str) -> anyhow::Result<()> {
    Ok(())
}

/// Write generated files to disk.
///
/// Rust files are formatted with `rustfmt` before writing so prek's `cargo fmt`
/// hook is a no-op on regenerated content. The embedded `alef:hash:<hex>`
/// value is a **per-file source+output** hash from
/// [`hash::compute_file_hash`]: `blake3(sources_hash || file_content_without_hash_line)`.
///
/// Hashes are written in two passes by the caller:
/// 1. `write_files` writes content with the header but **no hash line** (the
///    header marker is left in place so [`finalize_hashes`] can find it later).
/// 2. After every formatter has run, the caller invokes [`finalize_hashes`]
///    to inject the per-file hash. This means the embedded hash always
///    reflects the actual on-disk byte content and `alef verify` is a
///    pure read+strip+rehash+compare with no regeneration.
pub fn write_files(files: &[(Language, Vec<GeneratedFile>)], base_dir: &Path) -> anyhow::Result<usize> {
    Ok(write_files_report(files, base_dir)?.changed_count())
}

pub fn write_files_report(files: &[(Language, Vec<GeneratedFile>)], base_dir: &Path) -> anyhow::Result<WriteReport> {
    let mut prepared = std::collections::BTreeMap::<std::path::PathBuf, (Vec<u8>, bool)>::new();
    for file in files.iter().flat_map(|(_, lang_files)| lang_files.iter()) {
        let full_path = base_dir.join(&file.path);
        let (content, is_text) = if full_path.extension().is_some_and(|extension| extension == "jar") {
            (
                base64::engine::general_purpose::STANDARD
                    .decode(&file.content)
                    .with_context(|| format!("failed to decode base64 for {}", full_path.display()))?,
                false,
            )
        } else {
            let normalized = normalize_content(&full_path, &file.content);
            let normalized = if file.generated_header {
                ensure_generated_header(&full_path, &normalized)
            } else {
                normalized
            };
            (normalized.into_bytes(), true)
        };
        if let Some((existing, _)) = prepared.get(&full_path) {
            anyhow::ensure!(
                existing == &content,
                "multiple generators emitted different content for {}",
                full_path.display()
            );
            continue;
        }
        prepared.insert(full_path, (content, is_text));
    }
    let dirs: std::collections::BTreeSet<_> = prepared
        .keys()
        .filter_map(|path| path.parent().map(Path::to_path_buf))
        .collect();
    for dir in &dirs {
        std::fs::create_dir_all(dir).with_context(|| format!("failed to create directory {}", dir.display()))?;
    }

    let changed_paths = std::sync::Mutex::new(std::collections::HashSet::new());
    prepared
        .par_iter()
        .try_for_each(|(full_path, (content, is_text))| -> anyhow::Result<()> {
            if *is_text {
                let normalized = std::str::from_utf8(content).context("prepared generated text was not UTF-8")?;
                if let Ok(existing) = std::fs::read_to_string(full_path) {
                    let existing_body = crate::core::hash::strip_hash_line(&existing);
                    let normalized_body = crate::core::hash::strip_hash_line(&normalized);
                    if existing_body == normalized_body {
                        apply_shebang_chmod(full_path, normalized)?;
                        debug!("  unchanged: {}", full_path.display());
                        return Ok(());
                    }
                }
                atomic_write(full_path, content)?;
                apply_shebang_chmod(full_path, normalized)?;
            } else if std::fs::read(full_path).is_ok_and(|existing| existing == *content) {
                debug!("  unchanged: {}", full_path.display());
                return Ok(());
            } else {
                atomic_write(full_path, content)?;
            }
            changed_paths
                .lock()
                .expect("changed-path mutex poisoned")
                .insert(full_path.clone());
            debug!("  wrote: {}", full_path.display());
            Ok(())
        })?;

    Ok(WriteReport {
        expected_paths: prepared.into_keys().collect(),
        changed_paths: changed_paths.into_inner().expect("changed-path mutex poisoned"),
    })
}

/// Inject the per-file `alef:hash:` line into every alef-headered file in
/// `paths`. Run *after* every formatter (`format_generated`, `fmt_post_generate`).
///
/// The embedded hash covers the generation inputs and the final formatted file
/// body. Running this after all formatters makes manual output edits detectable
/// without treating Alef's own formatting pass as drift.
///
/// Files that don't carry the alef header marker (scaffold-once Cargo.toml,
/// composer.json, gemspec, package.json, lockfiles) are skipped — alef has
/// no claim on them.
pub fn finalize_hashes(
    paths: &std::collections::HashSet<std::path::PathBuf>,
    sources_hash: &str,
    alef_toml_bytes: &[u8],
) -> anyhow::Result<usize> {
    let inputs_hash = hash::compute_inputs_hash(sources_hash, alef_toml_bytes);

    let updated: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
    paths.par_iter().try_for_each(|path| -> anyhow::Result<()> {
        let content = match std::fs::read_to_string(path) {
            Ok(c) => c,
            Err(_) => return Ok(()),
        };
        let has_marker = content
            .lines()
            .take(10)
            .any(|line| line.contains("auto-generated by alef") || line.contains("Generated by alef"));
        if !has_marker {
            return Ok(());
        }

        let stripped = hash::strip_hash_line(&content);
        let file_hash = hash::compute_file_hash(&inputs_hash, &stripped);
        let final_content = hash::inject_hash_line(&stripped, &file_hash);

        if final_content == content {
            return Ok(());
        }

        atomic_write(path, final_content.as_bytes())?;
        apply_shebang_chmod(path, &final_content)?;
        updated.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        Ok(())
    })?;
    Ok(updated.into_inner())
}
