use super::*;

#[test]
fn content_marker_detected_for_both_header_spellings() {
    assert!(content_has_alef_marker(
        "// This file is auto-generated by alef. DO NOT EDIT.\n"
    ));
    assert!(content_has_alef_marker("# Generated by alef. Do not edit by hand.\n"));
    assert!(content_has_alef_marker("#ifndef X\n\n/* auto-generated by alef */\n"));
}

#[test]
fn content_marker_absent_for_unmarked_and_late_markers() {
    assert!(!content_has_alef_marker("fn handwritten() {}\n"));
    let late = "x\n".repeat(20) + "// auto-generated by alef\n";
    assert!(
        !content_has_alef_marker(&late),
        "a marker past the scanned prefix must not count, matching what verify reads"
    );
}

#[test]
fn content_marker_accepts_swift_capital_a_spelling() {
    // The live example a consumer proved was silently refused: capital "A" doesn't match the
    // lowercase-only `"auto-generated by alef"` literal the two-literal check used before this
    // fix. ~keep
    assert!(content_has_alef_marker(
        "// Auto-generated by alef — do not edit by hand.\n"
    ));
}

#[test]
fn content_marker_accepts_lowercase_generated_with_no_auto_prefix() {
    // The CITATION.cff / C# trait-bridge spelling: no "auto-" prefix at all, just
    // "generated by alef" lowercase. ~keep
    assert!(content_has_alef_marker(
        "# This file is generated by alef sync-versions; do not edit by hand.\n"
    ));
    assert!(content_has_alef_marker("// DO NOT EDIT — generated by alef\n"));
}

#[test]
fn content_marker_accepts_gos_code_generated_convention() {
    // Go's own "Code generated ... by <tool>. DO NOT EDIT." idiom -- alef should honour it
    // rather than fight it. ~keep
    assert!(content_has_alef_marker("// Code generated by alef — DO NOT EDIT.\n"));
}

#[test]
fn content_marker_accepts_standard_spelling_as_positive_control() {
    assert!(content_has_alef_marker(STANDARD_HEADER_LINE));
}

#[test]
fn content_marker_rejects_prose_that_only_shares_words_with_a_marker() {
    // Negative control mirroring the real false-positive incident documented in
    // `cli::pipeline::cleanup::has_alef_self_referential_header`: mentioning "alef" near
    // unrelated prose must not be enough. Proves the fix is a precise substring widen, not a
    // loose "contains alef" acceptance. ~keep
    assert!(!content_has_alef_marker("# Test apps are driven by alef\n"));
    assert!(!content_has_alef_marker(
        "// This module was generated for the alef project by a human.\n"
    ));
}

/// Enumerates every marker spelling alef's own emitters actually produce and asserts
/// [`content_has_alef_marker`] accepts each one, so a newly introduced spelling that the
/// predicate can't read back fails this test instead of silently freezing a file forever. Sourced
/// from real constants (not hand-copied prose) wherever an emitter already has one, plus the
/// literal `.jinja` templates that self-mark instead of using [`header`]/[`header_for_config`] --
/// see [`marker_spellings`] for the full, path-derived list. ~keep
#[test]
fn every_known_marker_spelling_is_recognized() {
    for spelling in super::marker_spellings::all_known_marker_texts() {
        assert!(
            content_has_alef_marker(spelling),
            "content_has_alef_marker must accept a marker alef itself emits:\n{spelling}"
        );
    }
}

#[test]
fn near_miss_marker_detects_a_word_order_variant() {
    let content = "// alef generated this file, do not edit\nfn main() {}\n";
    assert_eq!(
        near_miss_marker(content),
        Some("// alef generated this file, do not edit")
    );
}

#[test]
fn near_miss_marker_detects_a_hyphenated_variant() {
    // Mentions both words, but not as the contiguous "generated by alef" phrase.
    let content = "// This alef-generated file should not be edited.\nvalue\n";
    assert_eq!(
        near_miss_marker(content),
        Some("// This alef-generated file should not be edited.")
    );
}

#[test]
fn near_miss_marker_is_none_when_a_real_marker_already_matches() {
    // A matching line is never a near miss of itself -- the write guards only ever check for a
    // near miss once `content_has_alef_marker` has already come back false.
    assert_eq!(near_miss_marker(STANDARD_HEADER_LINE), None);
    assert_eq!(
        near_miss_marker("// Auto-generated by alef — do not edit by hand.\n"),
        None
    );
}

#[test]
fn near_miss_marker_is_none_for_unrelated_content() {
    assert_eq!(near_miss_marker("fn handwritten() {}\n"), None);
    // Mentions "alef" without "generated" -- not close enough to warrant a near-miss warning.
    assert_eq!(near_miss_marker("# Test apps are driven by alef\n"), None);
    // Mentions "generated" without "alef" -- likewise.
    assert_eq!(
        near_miss_marker("// This file was generated by a different tool.\n"),
        None
    );
}

#[test]
fn near_miss_marker_only_scans_the_leading_window() {
    let late = "x\n".repeat(20) + "// alef generated this\n";
    assert_eq!(
        near_miss_marker(&late),
        None,
        "a near miss past the scanned prefix must not count, matching content_has_alef_marker's own window"
    );
}
