//! Coverage for [`check_release_lock_freshness`], the release-gate counterpart to
//! `lock_freshness::check_generated_lock_freshness`.
//!
//! alef #1528: the diagnostic that module provides is correct and already caught real drift, but
//! only from inside `alef generate`/`alef all` -- and a drift whose cause lives in a hand-written
//! dependency alef never watches (the `tower-http` shape) never prompts a regen, so it never fired
//! before the affected consumer repos tagged and pushed. These tests exercise the same read-only
//! check reachable from `alef validate versions` instead, and prove it does NOT regress the one
//! case that must keep passing: a lock waiting on this release's own not-yet-published version.
//!
//! No cargo invocation anywhere: `check_release_lock_freshness` is pure file reads.

use super::*;
use crate::test_support::{git_add, git_init, write_file};

const CANONICAL: &str = "1.2.1";
const OLD_VERSION: &str = "1.2.0";

/// The alef marker every generated manifest carries, so `collect_alef_headered_paths` finds it
/// exactly the way it finds a real generated `Cargo.toml`.
const ALEF_MARKER: &str = "# This file is auto-generated by alef — DO NOT EDIT.\n";

/// Root single-package crate depending on a stale third-party requirement -- mirrors
/// `lock_freshness_tests`'s own `sample-core`/`sample-json` fixture, the founding `tower-http`
/// incident's shape: the dependency that goes stale is not the crate under test's own version at
/// all, it lives one manifest away in a hand-written dependency the generated e2e crate reaches
/// only by `path`.
fn write_root_manifest_with_stale_dependency(root: &std::path::Path) {
    write_file(
        root,
        "Cargo.toml",
        "[package]\nname = \"sample-core\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\n\
         sample-json = \"1.26\"\n",
    );
}

/// The alef-generated e2e crate, marked exactly like real generated output, depending on the
/// crate under test by path -- the indirection `relock_lockfiles_beside_changed_manifests` cannot
/// see through, since this manifest's own bytes never change when `sample-json` drifts.
fn write_generated_e2e_manifest(root: &std::path::Path) {
    write_file(
        root,
        "e2e/rust/Cargo.toml",
        &format!(
            "{ALEF_MARKER}[workspace]\n\n[package]\nname = \"sample-core-e2e-rust\"\nversion = \"0.1.0\"\n\
             edition = \"2024\"\n\n[dependencies]\nsample_core = {{ package = \"sample-core\", path = \"../..\" }}\n"
        ),
    );
}

fn write_stale_third_party_lock(root: &std::path::Path) {
    write_file(
        root,
        "e2e/rust/Cargo.lock",
        "version = 4\n\n\
         [[package]]\nname = \"sample-core-e2e-rust\"\nversion = \"0.1.0\"\n\n\
         [[package]]\nname = \"sample-core\"\nversion = \"0.1.0\"\n\n\
         [[package]]\nname = \"sample-json\"\nversion = \"1.25.0\"\n",
    );
}

/// The `test_apps/rust` shape every affected repo shared: an alef-generated, registry-mode
/// harness depending on the crate under test at exactly the canonical (about-to-release) version,
/// with a lock still pinning the previous release.
fn write_registry_mode_harness(root: &std::path::Path) {
    write_file(
        root,
        "Cargo.toml",
        &format!(
            "[workspace.package]\nversion = \"{CANONICAL}\"\n\n[workspace]\nresolver = \"2\"\n\
             members = [\"crates/sample\"]\n"
        ),
    );
    write_file(
        root,
        "crates/sample/Cargo.toml",
        "[package]\nname = \"sample\"\nversion.workspace = true\n",
    );
    write_file(root, "crates/sample/src/lib.rs", "");
    write_file(
        root,
        "test_apps/rust/Cargo.toml",
        &format!(
            "{ALEF_MARKER}[workspace]\n\n[package]\nname = \"sample-e2e-rust\"\nversion = \"{CANONICAL}\"\n\n\
             [dependencies]\nsample_alias = {{ package = \"sample\", version = \"{CANONICAL}\" }}\n"
        ),
    );
    write_file(root, "test_apps/rust/src/main.rs", "fn main() {}\n");
    write_file(
        root,
        "test_apps/rust/Cargo.lock",
        &format!(
            "version = 4\n\n[[package]]\nname = \"sample\"\nversion = \"{OLD_VERSION}\"\n\
             source = \"registry+https://example.invalid/index\"\n\n[[package]]\n\
             name = \"sample-e2e-rust\"\nversion = \"{CANONICAL}\"\n"
        ),
    );
}

/// The regression this module exists for: a stale lock whose cause is a hand-written dependency
/// alef never watches must fail the release gate, not merely get reported the next time someone
/// happens to run `alef generate`.
#[test]
fn check_release_lock_freshness_fails_on_a_drift_not_explained_by_a_pending_publish() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path();
    git_init(root);
    write_root_manifest_with_stale_dependency(root);
    write_generated_e2e_manifest(root);
    write_stale_third_party_lock(root);
    git_add(root, &["Cargo.toml", "e2e/rust/Cargo.toml", "e2e/rust/Cargo.lock"]);

    let error =
        check_release_lock_freshness(root, "0.1.0").expect("a lock stale for an unrelated reason must fail the gate");
    let message = format!("{error:#}");

    assert!(
        message.contains("sample-json"),
        "message must name the dependency: {message}"
    );
    assert!(message.contains("1.25.0"), "message must name the stale pin: {message}");
    assert!(
        message.contains("cargo update"),
        "message must name the remedy: {message}"
    );
}

/// The control that must keep passing: a lock left disagreeing only because it pins this
/// release's own not-yet-published version must NOT fail the gate -- `alef validate versions`
/// already tolerates that row, and this check must defer to the exact same exemption rather than
/// re-litigating it with a stricter, independently-derived rule.
#[test]
fn check_release_lock_freshness_tolerates_a_lock_blocked_on_the_pending_release() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path();
    git_init(root);
    write_registry_mode_harness(root);
    git_add(
        root,
        &[
            "Cargo.toml",
            "crates/sample/Cargo.toml",
            "crates/sample/src/lib.rs",
            "test_apps/rust/Cargo.toml",
            "test_apps/rust/Cargo.lock",
            "test_apps/rust/src/main.rs",
        ],
    );

    let outcome = check_release_lock_freshness(root, CANONICAL);

    assert!(
        outcome.is_none(),
        "a lock waiting on this release's own unpublished version must not fail the gate: {outcome:?}"
    );
}

/// The other control: a lock that resolves cleanly must report nothing at all.
#[test]
fn check_release_lock_freshness_passes_a_resolvable_lock() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path();
    git_init(root);
    write_root_manifest_with_stale_dependency(root);
    write_generated_e2e_manifest(root);
    write_file(
        root,
        "e2e/rust/Cargo.lock",
        "version = 4\n\n\
         [[package]]\nname = \"sample-core-e2e-rust\"\nversion = \"0.1.0\"\n\n\
         [[package]]\nname = \"sample-core\"\nversion = \"0.1.0\"\n\n\
         [[package]]\nname = \"sample-json\"\nversion = \"1.26.0\"\n",
    );
    git_add(root, &["Cargo.toml", "e2e/rust/Cargo.toml", "e2e/rust/Cargo.lock"]);

    let outcome = check_release_lock_freshness(root, "0.1.0");

    assert!(
        outcome.is_none(),
        "a lock that resolves must be reported clean: {outcome:?}"
    );
}
